name: Test & Deploy

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get Python
        uses: actions/setup-python@v6

      - name: Install Requirements
        run: |
          python -m install pip --upgrade pip
          python -m pip install requirements.txt

      - name: Run Tests
        run: pytest tests